CREATE TABLE IF NOT EXISTS `awake` (
  `char_id` INT UNSIGNED NOT NULL,
  `awake_lv` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `unlocked_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`char_id`)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `awake_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `char_id` INT UNSIGNED NOT NULL,
  `from_lv` TINYINT UNSIGNED NOT NULL,
  `to_lv` TINYINT UNSIGNED NOT NULL,
  `need_item` INT UNSIGNED NOT NULL,
  `need_amount` SMALLINT UNSIGNED NOT NULL,
  `success_rate` TINYINT UNSIGNED NOT NULL,
  `roll` TINYINT UNSIGNED NOT NULL,
  `is_success` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_char_id` (`char_id`)
) ENGINE=MyISAM;