//Main
npc: npc/beast/main/buff.txt
npc: npc/beast/main/jobmaster.txt
npc: npc/beast/main/platinum_skill.txt
npc: npc/beast/main/kafra.txt
npc: npc/beast/main/rental.txt
npc: npc/beast/main/warper.txt
npc: npc/beast/main/style.txt
npc: npc/beast/main/shop.txt
npc: npc/beast/main/pvp.txt
//npc: npc/beast/main/warp.txt
npc: npc/beast/main/guildsystem.txt
npc: npc/beast/main/itemcode.txt

//Shop
npc: npc/beast/shop/cashshop.txt
//npc: npc/beast/shop/equiptment.txt
//npc: npc/beast/shop/weapon.txt
//npc: npc/beast/shop/headgear.txt
//npc: npc/beast/shop/card.txt
npc: npc/beast/shop/bonusshop.txt

//Merchant
npc: npc/beast/merchant/refine.txt
npc: npc/beast/merchant/card_remove.txt
npc: npc/beast/merchant/enchant.txt
npc: npc/beast/merchant/homunculus.txt
npc: npc/beast/merchant/pack_elu_ori.txt
npc: npc/beast/merchant/toolshop.txt
npc: npc/beast/merchant/pet_evo.txt

//Quest
npc: npc/beast/quest/huntingmission.txt
npc: npc/beast/quest/getsetboss.txt

//System
npc: npc/beast/system/rankstatus.txt
//npc: npc/beast/system/menu.txt
npc: npc/beast/system/find_monster_cfg.txt
npc: npc/beast/system/find_monster_sys.txt
npc: npc/beast/system/clock.txt
npc: npc/beast/system/vip.txt
//npc: npc/beast/system/goldpc.txt
npc: npc/beast/system/testdamage.txt
npc: npc/beast/system/new_bmp.txt
npc: npc/beast/system/daynight.txt
npc: npc/beast/system/webhook.txt

////Training
//npc: npc/beast/training/trainingshop.txt
//npc: npc/beast/training/training7vs7(CH1).txt
//npc: npc/beast/training/training7vs7(CH2).txt
//npc: npc/beast/training/training7vs7(CH3).txt
//npc: npc/beast/training/training7vs7(CH4).txt
//npc: npc/beast/training/training12vs12(CH5).txt
//npc: npc/beast/training/training12vs12(CH6).txt
//npc: npc/beast/training/training12vs12(CH7).txt
//npc: npc/beast/training/training12vs12(CH8).txt

//Ranking
npc: npc/beast/ranking/pvpladder.txt
npc: npc/beast/ranking/mvpladder.txt
npc: npc/beast/ranking/woeladder.txt
npc: npc/beast/ranking/empladder.txt
npc: npc/beast/ranking/resetladder.txt

//Function
npc: npc/beast/function/autopot.txt
npc: npc/beast/function/plagiarize.txt
npc: npc/beast/function/soulinkerscroll.txt
npc: npc/beast/function/open_door.txt

//Guild War
npc: npc/beast/guildwar/Itemwar.txt
npc: npc/beast/guildwar/Recall.txt
npc: npc/beast/guildwar/Warp_guild.txt
npc: npc/beast/guildwar/guild_config.txt
npc: npc/beast/guildwar/guild_warp_config.txt
npc: npc/beast/guildwar/auto_guildwar.txt
npc: npc/beast/guildwar/warp_guildwar_custom.txt
npc: npc/beast/guildwar/flags.txt

//Newbie
npc: npc/beast/newbie/novice.txt

//Event
npc: npc/beast/event/endlesstower.txt
npc: npc/beast/event/floorislarva.txt
npc: npc/beast/event/dice_event.txt
npc: npc/beast/event/talent_match.txt
npc: npc/beast/event/ahateamdefend.txt

//Mob
npc: npc/beast/mob/dic_dun.txt